[package]
name = "advent-of-Code-2022"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/library/mod.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.14"
